### ISSUE TITLE
ISO "ALPHA-2 Code

### ISSUE THREAD

**Issue by marianoarga** [BaseflowIT/flutter-geolocator#101]
Is there any way I can get the 2 digits country ISO code? like "AR", "US", etc. from this plugin once it geolocates the device?

Thank you.

**Comment by mvanbeusekom** [comment]
Hi @marianoarga, 

Yes this is possible. To do so you'll first have to acquire the co-ordinates (using the `getCurrentPosition`, `getLastKnownPosition` methods or a location update from the `getPositionStream` method). 

Once you have the co-ordinations (the `latitude` and `longitude` fields from the `Position` class) you can pass them into the `placemarkFromCoordinates` method. This will return an instance of `Placemark` class which contains a field `isoCountryCode` which contains the ALPHA-2 country code if a country could be resolved for the supplied co-ordinates (otherwise the field will be `null`).
