### ISSUE TITLE
 await Geolocator().getCurrentPosition blocks.

### ISSUE THREAD

**Issue by zedan185** [BaseflowIT/flutter-geolocator#117]
## 💬 Questions and Help
I am using the following code in which the statement
` Position position =  await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.low);`
 just hangs and does not reach the next statement
```
This is what I am doing

Future<Position> getLocation() async
{
    Geolocator geolocator = Geolocator()..forceAndroidLocationManager = true;
    GeolocationStatus geolocationStatus  = await geolocator.checkGeolocationPermissionStatus();
    Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.low);
    return position;
}
```
Here are the details of my env.

$ flutter doctor -v
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.6.0 at /Users/adam/Flutter/flutter
    • Framework revision 9299c02cf7 (6 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/adam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/adam/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4445.29

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

Any suggestions on why the statement just hangs ?

**Comment by zedan185** [comment]
After doing a clean cache it worked. Closing this issue.

**Comment by HerrNiklasRaab** [comment]
@zedan185 What steps did you do exactly? I have the same problem.

**Comment by mleonhard** [comment]
I'm hitting this problem with Android Emulator API 21 & 22 with Google APIs.  The problem doesn't happen on API 28 with Google APIs.  I haven't tested any API versions in between.  After spending many hours, I've given up on a fix.

Clearing the gradle cache did nothing (`rm -rf ~/.gradle/caches/` from [this answer](https://stackoverflow.com/a/23029580)).  `flutter clean` also did nothing.

I believe the root cause is this: The firebase_messaging Flutter plugin checks if Google Play Services is installed and then tries to use it to get the location.  But if Google Play Services is not logged in, [Google Maps Geolocation API](https://developers.google.com/maps/documentation/geolocation/intro) refuses the request.  Or maybe the Google Play Services client library doesn't send it.  I presume that Google allows the API to work only when it can record the user's location for later monetization via ads.  Unfortunately, no error is returned through the plugin to the calling Dart code.

So we have three configurations:
1. Google Play Services is not installed.  flutter_geolocator plugin uses Android Location Manager which waits for a GPS signal.
2. Google Play Services is installed but not logged in.  flutter_geolocator plugin uses Google's FusedLocationProvider which never returns.  This is the behavior reported in this bug.
3. Google Play Services is installed and user logged in.  flutter_geolocator plugin uses Google's FusedLocationProvider which successfully gets the location from Google Play Services.

I've decided to use a workaround of waiting 5 seconds for the Google Play Services call and then giving up and trying for a GPS signal.  A user in scenario 3, with a poor network connections that makes the API call take longer than 5 seconds, will have to wait for a GPS fix, which may not succeed.  I'm ok with this because my app allows the user to retry the operation.

```
print('getPosition() calling Geolocator.getCurrentPosition()');
final geolocator.Position position = await new geolocator.Geolocator()
    .getCurrentPosition(desiredAccuracy: geolocator.LocationAccuracy.best)
    .timeout(Duration(seconds: 5), onTimeout: () {
  print('getPosition() timeout. Trying Android Location Manager');
  final geolocator.Geolocator geolocatorObj = new geolocator.Geolocator();
  geolocatorObj.forceAndroidLocationManager = true;
  return geolocatorObj.getCurrentPosition(
      desiredAccuracy: geolocator.LocationAccuracy.best);
});
print('getPosition() got position=$position');
```

Still, the better fix would be for the flutter_geolocator to detect if no user account is configured and immediately fall back to GPS.  I looked at the code to try to make a PR, but I don't know enough about Android coding.  The APIs are very complex and poorly documented.

**Comment by Jay-Jeong1988** [comment]
In my case, changing LocationAccurracy from low to best solved the issue.

**Comment by ArnoSoontjens** [comment]
@Jay-Jeong1988 's answer is correct. Go to settings -> Security & Location -> Location -> Mode -> Check 'High Accuracy' and 'Agree'. I found this can also be solved by requesting (from java code) a GPS update with accuracy set to high, which will enable this setting without having to go through settings.

**Comment by ollydixon** [comment]
I'm seeing this issue after upgrading to Xcode 11.4.  Tried 3 location libraries now, all broken on iOS.

**Comment by christmo** [comment]
In the Simulator, I needed to send a custom locations in the menu bar "Features" -> "Location" -> "Custom Location", and it works for me.

**Comment by dhairya786** [comment]
> In my case, changing LocationAccurracy from low to best solved the issue.

yessss

**Comment by mawg** [comment]
> In my case, changing LocationAccurracy from low to best solved the issue.

After hours of search & recoding, this is what solved it for me, in Visual Studio Code, Android Emulatoor (specifically, exercise 13, Clima, from London App Brewery's Udemy course, The Complete 2020 Flutter Development Bootcamp with Dart.  Yay!!  (strangler, my Android manifest only requests coarse location! But, who cares? It wurkz !!)

**Comment by JohnvdL** [comment]
+1 for christmo's solution!

**Comment by ankurdhoom** [comment]
During debugging what I found that changing LocationAccurracy from low to best worked but still I was tyrying to find out what is happening when used low. 

Try something try / catch , like below worked...so I believe it is something to do with through ...

```
try {
      Position position =
          await getCurrentPosition(desiredAccuracy: LocationAccuracy.low);
   
    } catch (e) {
      print('Location not shared');

```

**Comment by theblakersfield** [comment]
I fixed my problem, In the emulator (android 10) I went to settings -> location -> advanded -> Google location accuracy -> turned it off. It says that it uses wifi/etc to improve the accuracy. With it turned off it will only uses gps for location.

**Comment by Sultanic** [comment]
I fixed my problem by changing the Android permissions from `ACCESS_COARSE_LOCATION` to `ACCESS_FINE_LOCATION`.  
I completely missed the note in the README  
> **NOTE:** Specifying the `ACCESS_COARSE_LOCATION` permission results in location updates with an accuracy approximately equivalent to a city block. **_It might take a long time (minutes) before you will get your first locations fix_** as `ACCESS_COARSE_LOCATION` will only use the network services to calculate the position of the device. More information can be found [here](https://developer.android.com/training/location/retrieve-current#permissions).

**Comment by codec-abc** [comment]
Can we reopen this? I have the same behavior and I noticed that the blocking call resolve just fine if I use hot reload and do a hot restart at least once. So, it seems there is something tricky under the hood.

**Comment by FMorschel** [comment]
Having the same issue on my Pixel C emulator with SDK 30 (Andorid 11), havent tryied other emulators) and on my Samsung Galaxy S20 FE (Android 11 as well) any progress in figuring out whats the actual problem?
