### ISSUE TITLE
Add Android M Permission Example 

### ISSUE THREAD

**Issue by feinstein** [BaseflowIT/flutter-geolocator#141]
I just read the Readme.md and the permissions part only describes the old permission system Android used to have.

After Android M, developers have to ask for permission on the fly, and permissions can be revoked at any time. 

Thus, I think it will be interesting to add examples on how to prompt for location permissions, as the Android M defines.

**Comment by mvanbeusekom** [comment]
@feinstein not really sure what you mean by this, could you elaborate more on what you mean with "Android M, developers have to ask for permission on the fly"? 

By default the Geolocator plugin requests for permissions just-in-time. Meaning if you try to request a location and the user has not been prompted with a permission request before (for that particular App) the Geolocator plugin will ask for the permissions to access the location data. 

If you want to have a bit more control on the moment permissions are requested you can directly integrate the `permission_handler` plugin (see https://github.com/baseflowit/flutter-permission-handler).

**Comment by feinstein** [comment]
Oh that information is precisely what I felt was missing.

Before Android M, we just had to put the permissions on the Manifest, then when the user downloaded the app the permissions where given automatically and couldn't be revoked. 

After Android M, we need to add the permissions to the Manifest and check/ask for permission every time we need to use the locations, since permissions on Android M can be revoked at any moment.

**Comment by mvanbeusekom** [comment]
@feinstein thanks for your feedback, I will try to add this more clearly in the documentation. Good news for you is that you don't have to worry about permission management since the Geolocator plugin will take care of it for you (except from adding the permissions to the manifest file of course).

One thing to note here, once the user explicitly denies access to the location services, the Geolocator will not ask for permissions again. If you do want to alert the user that access to the location services are disabled you can use the `checkPermissionStatus ` and/ or `shouldShowPermissionRationale` methods of the `permission_handler` plugin.
