### ISSUE TITLE
Android (maybe iOS), doesn't ask to open GPS when it's turned off

### ISSUE THREAD

**Issue by jaumard** [BaseflowIT/flutter-geolocator#170]
## 🔙 Regression

I think it's a regression but I might be wrong ^^

### Old (and correct) behavior
When calling `getCurrentPosition()` if GPS is turned off, ask user to turn it on

### Current behavior
Throw PlatformException saying GPS is turned off

If it's the current behavior, how ask the user to turn it on after checking `checkGeolocationPermissionStatus` ? There no method on the geolocator for doing that :(

### Configuration

**Version:** 2.1.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by jaumard** [comment]
But now Android allow you to have a popup to activate the GPS (instead of just redirecting to settings), more user friendly and user don't leave the app. On iOS it's rare that user disable their GPS as it's well hidden on phone setting lol

**Comment by ibrierley** [comment]
You can afaik, but I don't think there would be any way via flutter/dart. You'd have to write some java stuff.

**Comment by mvanbeusekom** [comment]
@jaumard since version 4 you can manually check if the location services are enabled or not using the `isLocationServiceEnabled` method. 

Or more advanced options are available when using the `LocationPermissions` plugin directly (which is included by the Geolocator), more info: https://github.com/BaseflowIT/flutter-permission-plugins/tree/develop/packages/location_permissions.
