### ISSUE TITLE
Is there a reason for witch the plugin is written using Swift?

### ISSUE THREAD

**Issue by long1eu** [BaseflowIT/flutter-geolocator#178]
https://github.com/flutter/flutter/issues/17999

**Comment by mvanbeusekom** [comment]
The main reason is that we don't (want to) understand Objective-C and because it is the recommended language by Apple (quoted from [here](https://developer.apple.com/swift/)): 

>Swift is a successor to both the C and Objective-C languages. It includes low-level primitives such as types, flow control, and operators. It also provides object-oriented features such as classes, protocols, and generics, giving Cocoa and Cocoa Touch developers the performance and power they demand.

Unfortunately when we started developing we didn't realize (like so many of us) that using Swift and Flutter would have such a big penalty in the final app size. Now we are so far in that we don't have the knowledge or time to translate the plugins (see also [permission_handler](https://github.com/BaseflowIT/flutter-permission-handler)) back to Objective-C.

**Comment by long1eu** [comment]
Are welcoming pull requests on this?

**Comment by mvanbeusekom** [comment]
Yes we definitely do, if you would also be willing to take the [permission_handler](https://github.com/BaseflowIT/flutter-permission-handler) into account.

**Comment by long1eu** [comment]
Perfect, let’s start there.
