### ISSUE TITLE
GeoLocator depends on permission_handler 2.2.0 but we are using 3.0.0

### ISSUE THREAD

**Issue by AlexandreRoba** [BaseflowIT/flutter-geolocator#203]
## 🐛 Bug Report
We have dependency on our project to permission_handler 3.0.0.
when adding geolocator 3.0.0 we are getting this error message:
```bash
Because superapp depends on geolocator ^3.0.0 which depends on permission_handler ^2.2.0, permission_handler ^2.2.0 is required.

So, because superapp depends on permission_handler ^3.0.0, version solving failed.
```

### Expected behavior
Any chance to make a release of geo locator that make use of the latest version of permission handler?

**Version:** 3.0.0

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by tsjly** [comment]
You can delete permission_handler in pubspec.yaml directly.

**Comment by just-peteking** [comment]
I have the same issue, permission_handler: ^3.0.0 supports AndroidX but GeoLocator only supports 2.2.0.

GeoLocator needs to upgrade its dependencies.

**Comment by pneves001** [comment]
permission_handler 2.2.0 is broken on the latest version of flutter. Will not build. 

[        ] WARNING: This version of device_info will break your Android build if it or its dependencies aren't
compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may
be unrelated.
[        ]          *********************************************************
[        ] D8: Program type already present: android.support.v4.app.INotificationSideChannel
[ +184 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
[   +2 ms] > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/6
.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/8
.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/9
.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
0.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
1.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
2.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
3.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
4.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
5.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
6.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
7.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
8.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
9.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/2
0.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/2
1.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/2
2.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/2
3.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/2
7.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/2
8.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/2
9.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
0.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
1.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
2.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
3.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
4.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
5.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
6.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
7.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
8.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/3
9.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
0.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
1.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
2.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
3.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
4.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
5.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
6.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
7.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
8.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/4
9.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
0.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
1.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
2.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
3.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
4.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
5.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
6.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
7.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
8.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/5
9.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/6
1.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/6
2.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/6
3.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/6
4.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/6
6.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/6
8.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/6
9.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
0.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
1.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
2.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
3.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
4.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
5.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
6.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
7.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
8.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/7
9.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/8
0.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/8
1.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/8
2.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/8
3.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/8
5.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/8
6.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/8
7.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/8
9.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/9
0.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/9
2.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/9
3.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/9
4.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/9
5.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/9
7.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/9
8.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
00.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
01.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
02.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
03.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
05.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
06.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
07.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
08.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
09.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
10.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
11.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
14.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
15.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
16.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
17.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
18.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
19.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
20.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
21.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
22.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
23.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
24.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
29.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
30.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
31.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
32.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
33.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
34.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
35.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
36.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
37.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
38.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
39.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
40.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
41.jar,
/Users/philipneves/NevesSoftware/loyalitySystem/loyality/build/app/intermediates/transforms/dexBuilder/debug/1
42.jar
[  +19 ms]   Learn how to resolve the issue at
https://developer.android.com/studio/build/dependencies#duplicate_classes.
[        ]   Program type already present: android.support.v4.app.INotificationSideChannel
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more
log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 3s
[ +341 ms] Running Gradle task 'assembleDebug'... (completed in 4.5s)
[        ] *******************************************************************************************
[        ] The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
[        ] See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ] *******************************************************************************************
[   +4 ms] "flutter run" took 10,416ms.
[        ] "flutter run" took 10,416ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:462:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:331:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:378:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:308:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#26     Future._complete (dart:async/future_impl.dart:473:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#29     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#30     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#31     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#37     Future._complete (dart:async/future_impl.dart:473:7)
#38     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#39     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by kyleodev** [comment]
The same problem, please fix.

> You can delete permission_handler in pubspec.yaml directly.

Couldn't find it.

**Comment by mvanbeusekom** [comment]
Dependecies have been updated in version 3.0.1
