### ISSUE TITLE
Geolocator >= 4. version breaks permission_handler

### ISSUE THREAD

**Issue by marinat** [BaseflowIT/flutter-geolocator#250]
## 🐛 Bug Report

I created project with google map, after requesting permissions via permission_handler I wanted to find my current position, but got 'Flutter result object is null.'

### Expected behavior
All works fine on 3.0.1
### Reproduction steps
Create application with map, permission_handler and geolocator. Try to get position after getting permissions. You'll get this error.
### Configuration
Android M
**Version:** 4.0.0

**Platform:** 
- [ ] :robot: Android

P.S. Should I report this issue to permission_handler developers?

**Comment by japborst** [comment]
They switched to https://pub.dartlang.org/packages/location_permissions, which is just the location permission part from the original `permission_handler` package by the same devs.

With that package, one only needs to add permissions to the location in `info.plist` instead of everything.

**Comment by mvanbeusekom** [comment]
@marinat, as @japborst already mentioned we indeed switch from using the `permission_handler` plugin to the `location_permissions` plugin, solving some issues that meanly had to do with App submission to the Apple AppStore.

You can replace the `permission_handler` plugin with the `location_permissions` plugin if you want to request permissions yourself. Otherwise you can remove the `permission_handler` plugin all together and trust the `geolocator` plugin to handle permissions for you (of course you will still have to add the required configuration to your `Info.plist` and `AndroidManifest.xml` files.
