### ISSUE TITLE
listening on getPositionStream does not work if location permission is denied

### ISSUE THREAD

**Issue by aytunch** [BaseflowIT/flutter-geolocator#270]
```
StreamSubscription<Position> positionStream = geolocator.getPositionStream(locationOptions).listen(
    (Position position) {
        print(position == null ? 'Unknown' : position.latitude.toString() + ', ' + position.longitude.toString());
    });
```
Let's say App launches with location permission in denied state. 
In this case, the code above does not really start a `StreamSubscription`
Even after putting the app into background(without killing the app) and opening iOS setting and granting location permission and going back to the app, the `StreamSubscription` does not dispatch new positions and we need to create the `positionStream` again in order to get location values.

I propose, if possible, to allow listening to the stream even when permission denied so that after granting location access new `Position`s keep on coming.

Or I am not doing something right?

**Comment by MorochoRochaDarwin** [comment]
> ```
> StreamSubscription<Position> positionStream = geolocator.getPositionStream(locationOptions).listen(
>     (Position position) {
>         print(position == null ? 'Unknown' : position.latitude.toString() + ', ' + position.longitude.toString());
>     });
> ```
> 
> Let's say App launches with location permission in denied state.
> In this case, the code above does not really start a `StreamSubscription`
> Even after putting the app into background(without killing the app) and opening iOS setting and granting location permission and going back to the app, the `StreamSubscription` does not dispatch new positions and we need to create the `positionStream` again in order to get location values.
> 
> I propose, if possible, to allow listening to the stream even when permission denied so that after granting location access new `Position`s keep on coming.
> 
> Or I am not doing something right?

On Android and iOS the user must grant access to the location, otherwise your app will not be able to use the geolocation functions.

**Comment by mvanbeusekom** [comment]
Hello @aytunch, thank you for contacting us. As far as I know the user really needs to first allow the App to access the location services before we can continue to query the native location SDKs. 

Meaning until we have access we cannot subscribe to receive location updates and thus also cannot provide a stream back to you which potentially listens for updates as soon as the right permissions are granted.

I guess technically we could implement some dummy stream and merge it with a real stream when permissions change but this will be a cumbersome task (especially since the platforms also not supply and notification system on permission changes). Besides that is also moves away from the recommended way of implementing the location SDKs on the native platforms which is something we try to stick to as close as possible.

Please if you have more information let me know.

**Comment by aytunch** [comment]
@mvanbeusekom Thanks for the clarification. I made my own permission change callbacks and when permision is granted I listen to geolocator stream and when denied I cancel subscription. Right now works fine.
