### ISSUE TITLE
5.01  Allow developers to specify the permission level?

### ISSUE THREAD

**Issue by nicolasjon** [BaseflowIT/flutter-geolocator#281]
## 💬 Questions and Help

5.01

Allow developers to specify the permission level they want to use when requesting permissions on iOS.

How do we specify this?

Thanks
Nicolas

**Comment by mvanbeusekom** [comment]
Hello Nicolas,

Since version 5.0.1 the methods `getCurrentPosition`, `getLastKnownPosition` and `getPositionStream`  have a new optional named parameter called `locationPermission`. 

I see now that while doing the code review I have missed that direct use of the `LocationPermissionLevel ` enum from the `location_permissions` plugin. This should have been abstracted away by the `GeolocationPermission` enum, so we will have to make a fix for this unfortunately.
