### ISSUE TITLE
iOS App store advising NSLocationAlwaysUsageDecription key is missing from info.plist file

### ISSUE THREAD

**Issue by MattL-NZ** [BaseflowIT/flutter-geolocator#290]
## 🐛 Bug Report

I am building an app using the geolocator plugin version 5.0.1.
Everything works fine in the app and location is able to be obtained successfully. 
When I upload my app to the iOS app store for testing (TestFlight), I get an email each time saying the following:

> Your delivery was successful, but you may wish to correct the following issues in your next delivery:
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

I am still able to test the app as it goes through to the app store but it would be good to not have to see this issue each time.

I understand that I could just add in that key into the info.plist file but I only need to know the users location when they are in the app. I am setting my locationPermissionLevel to be ```LocationPermissionLevel.locationWhenInUse```

Is there a way to get around this without needing to use all of the location keys in the info.plist file?

### Code
```
try {
    Position position = await Geolocator().getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high, 
        locationPermissionLevel: LocationPermissionLevel.locationWhenInUse
    );

      if (isMarkerShown != null && position != null) {
        mapController.clearMarkers();
        mapController.addMarker(MarkerOptions(
          position: LatLng(position.latitude, position.longitude)));
        searchByLatLng(LatLng(position.latitude, position.longitude), context);
        isMarkerShown = true;
      }
      error = null;
    } on PlatformException catch (e) {
      if (e.code == 'PERMISSION_DENIED') {
        print("Permission to location was denided");
      } else if (e.code == 'PERMISSION_DENIED_NEVER_ASK') {
        error = 'Permission denied - please ask the user to enable it from the app settings';
      }
    }
  } 
```

**Version:** 5.0.1

**Platform:** 
- [x] :iphone: iOS

**Comment by mvanbeusekom** [comment]
@MattL-NZ the problem here is that our code base does include calls to the `requestAlwaysAuthorization()` method to make it convenient for our users to easily switch between implementations. So the static code analyses tools from Apple find this call and alert us that we need to include a purpose string in the `Info.plist` file. 

So we made the decision that having to include the extra line in the `Info.plist` out ways the effort for developers to having to implement a custom permissions requesting scheme. So for now we suggest to include the key in you `Info.plist` (if you don't use it in the App you can use any kind of description, I'd suggest something like "This App doesn't use location services in the background").

If you have any idea's on how we could solve this issue we would be very happy to hear from you.

**Comment by ycherniavskyi** [comment]
What about the same way as it implemented in [permission_handler](https://pub.dev/packages/permission_handler) - via `post_install` hook in `Podfile`?

**Comment by albertolina** [comment]
I agree with @ycherniavskyi

**Comment by mahmutpinarbasi** [comment]
Any updates on this one @mvanbeusekom?
