### ISSUE TITLE
Distance Between : Why a Future ?

### ISSUE THREAD

**Issue by Robouste** [BaseflowIT/flutter-geolocator#291]
## 🏗 Enhancement Proposal

This is more a discussion than a real proposal. I'm new to Flutter so I might lack some knowledge, that's why I'm openning this.

DistanceBetween returns a future. I don't really see why because nothing async should be involved in this process, it is math, and it forces us to write extra code to get the result.

Why is it a Future ?

**Comment by mvanbeusekom** [comment]
The reason it is a async method is because we make a call to the native side and let the native SDKs do the calculations. Since calls to the native side are always async this method also has become async.

The calculation of the distance between points is indeed just math, however we opted to not include our own calculation logic and choose to reuse the SDK methods already provided by Google and Apple.
