### ISSUE TITLE
google_play_services_widget.dart not found

### ISSUE THREAD

**Issue by uggih** [BaseflowIT/flutter-geolocator#304]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by uggih** [comment]
google_play_services_widget.dart not found at pages

**Comment by sjoerd0301** [comment]
Hi,

This file has been removed since version 2.0.0.
please upgrade or pull the latest version.
You could find the latest version [HERE](https://github.com/BaseflowIT/flutter-geolocator/tree/82e1f68e398208a68c11efdc71d1054912e9597e/example/lib/pages) if you need it.

please use the google api availability plugin, [here](https://pub.dev/packages/google_api_availability).
