### ISSUE TITLE
Listening again on getPositionStream does not use last known location

### ISSUE THREAD

**Issue by sanekyy** [BaseflowIT/flutter-geolocator#326]
## 🐛 Bug Report

If I create second subscription on getPositionStream after first subscription which already got location, then second location don't receive location while it will not changed.

### Expected behavior
Second subscriptin immidiate receive last known location if it's exists.

### Reproduction steps
1) Create first subscription on getPositionStream
2) Receive location
3) Create second subscription on getPositionStream
4) Second subscription will receive location only when location will change

### Configuration

**Version:** 5.1.3

**Platform:** 
- [x] :robot: Android

**Comment by audkar** [comment]
When I subscribe to `getPositionStream` I do not expect to get old/stale data. My expectation is to receive only new location events. In some cases your suggested behavior can introduce very severe issues. One example could be driving navigation app. If second subscription is made and it gets 10s old data, that can be deal breaking problem for navigation. App user can be passed some road crossing already.
So in other words this API change would be breaking for existing users because they would have start to check if first items is not too far in the past.

If you want on subscription get previous location you can easily achieve same behavior yourself:
```
Stream<Position> getPositionStreamWithLast() {
    return StreamGroup.merge([
      Stream.fromFuture(_geolocator.getLastKnownPosition(<...>))
          .where((it) => it != null),
      _geolocator.getPositionStream(<...>)
    ]);
}
```

**Comment by sanekyy** [comment]
I understand you and generally agree, but first call of `getPositionStream ` immediately return location and it's also maybe 10s old data.

**Comment by audkar** [comment]
It depends which desired accuracy you have chosen when subscribed to `getPositionStream` https://developer.android.com/guide/topics/location/strategies#Flow

e.g. you can get cached (old) position retrieved from cell network. But you get only if your phone is still connected to that tower. So device knowns that coordinates are still valid.

**Comment by sanekyy** [comment]
I just state the fact that the `getPositionStream` method works differently when called with the same parameters.

**Comment by StijnWoerkom** [comment]
As @audkar describes you need to build the flow which suits your app the best. If we would change the API to suit your behavior we would receive new issues and since we want to achieve what is best for the geolocator plugin, it would be a silly change. If you have new questions about this subject, you can file them here or we can close this issue.
