### ISSUE TITLE
Unidentified issue at https://pub.dev/packages/geolocator

### ISSUE THREAD

**Issue by miltondavila** [BaseflowIT/flutter-geolocator#335]
## 🐛 Bug Report

The geolocator package in this website is having some issues, which have decreased it's overall score to 64/100:

https://pub.dev/packages/geolocator#-analysis-tab-

### Expected behavior

The overall score should be over 90/100.

### Reproduction steps

Visit the following website:

https://pub.dev/packages/geolocator#-analysis-tab-

![image](https://user-images.githubusercontent.com/3312235/66260358-55ef7800-e783-11e9-8261-1118d2c6695f.png)

### Configuration

**Version:** 5.1.4

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by miltondavila** [comment]
It seems that the pubspec.yaml has been updated and set meta ^1.1.7.  Perhaps, this can fix the issue once pub.dev analyzes the package again.

However, the README.md file is still showing an old geolocator version in the "Usage" section:

dependencies:
  geolocator: ^5.1.3

Should this be changed to the current version?

dependencies:
  geolocator: ^5.1.4

![image](https://user-images.githubusercontent.com/3312235/66260668-22165180-e787-11e9-8080-fb79e9ea7348.png)

**Comment by StijnWoerkom** [comment]
@miltondavila Thank you for reporting this issue. The uploaders on the website from our side are very busy with other projects. We will try to update the website as quick as possible.

**Comment by mvanbeusekom** [comment]
@miltondavila thank you for informing us regarding the statistics. It indeed turns out that the static code analysis on pub.dev doesn't support the latest Flutter SDK yet. 

We just released the a new hotfix of the Geolocator (5.1.4+1) which solved the issue (indeed by simply downgrading to meta 1.1.7).

I have also updated the README.md to match the correct version number.
