### ISSUE TITLE
W/Activity(11227): Can reqeust only one set of permissions at a time

### ISSUE THREAD

**Issue by nicolasjon** [BaseflowIT/flutter-geolocator#58]
## 🐛 Bug Report

When running app for the first time on Android
W/Activity(11227): Can reqeust only one set of permissions at a time
shows in the console log.

Using 
geolocator: "^1.4.0"

Thanks.

**Comment by mvanbeusekom** [comment]
Thanks for the feedback. When you mention “when running app” do you mean the example app or an app you created yourself?

I can imagine this happens when you execute the `getCurrentPosition` and the `getPositionStream` directly (or close) after each other and both want to request the necessary permissions. I would say this would not be a common situation but indeed happens in the example app. 

Anyway this will be something we will look into. Additional information on the “app” is appreciated ;)

**Comment by nicolasjon** [comment]
Hi,

Yes the calls are after each other. Do I need to run both or will
getpositionStream return the first it has? I know stream generally wait for
a change. so if stationary an update my never arrive?
At the moment when the app starts they are racing..

Cheers..

Nicolas
