### ISSUE TITLE
getPositionStream() should return Stream without wrapping it into Feature

### ISSUE THREAD

**Issue by audkar** [BaseflowIT/flutter-geolocator#71]
## 🏗 Enhancement Proposal

`Geolocator.getPositionStream()` should return Stream without wrapping it into Feature. 

This would revert breaking API change which was introduced in `1.5.0`. So breaking API after breaking API :thinking: 

### Pitch

I am very new to Dart but I think it is possible to make single stream without wrapping it into `async`. This could be achieved by converting Feature to Stream and then chaining latestResult to new Stream with StreamTranformation.

If using [RxDart class](https://pub.dartlang.org/documentation/rxdart/latest/rx/SwitchMapStreamTransformer-class.html):
```
Stream<SomeValue> stream = someFeature.asStream().transform(SwitchMapStreamTransformer(otherStreamMapper)))
```
So `RxDart` dependency can be introduced or just SwitchMap logic copied to project.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by audkar** [comment]
Also introducing braking change should increase `major` version number. Everyone is using format for dependencies in pubscpec.yaml like this: `geolocator: '^1.4.0'`. Which means that project is not going to compile after this lib release for all people who is using this dependency even they manually do not update to 1.5.0.

**Comment by mvanbeusekom** [comment]
@audkar thank you very much for your feedback, we are also pretty new to Dart and learning a long the way ;).

Your suggested solution also popped up in my mind, however I wasn't sure if things like unsubscribing from the stream are correctly passed through to the original stream (which is important since the platform specific code needs to respond to these events. So to prevent including all kind of management code to take care of this I choose to simple return a `Future` so I don't have to worry about this.

However you question triggered me to investigate a bit deeper and since I couldn't find an answer myself, I posted a question on (SO)[https://stackoverflow.com/questions/51891906/is-there-a-way-to-prevent-having-to-await-an-async-method-returning-a-stream] to see if someone can help us out. I will let you known how this goes.

**Comment by escamoteur** [comment]
Looking at the readme and the SO reply it looks as this issue is solved?

**Comment by mvanbeusekom** [comment]
@escamoteur no that is not the case. The README is not correct here and you should still await the call to the `getPositionStream` method.

Indeed on SO they offer a good solution to this problem, but it will involve yet again a breaking change (to undo the earlier breaking change). So we postponed this change to a later version which will contain a bit more substantial changes (since this is not really a bug, just makes the live of other developers a bit easier).
