### ISSUE TITLE
Both Android Fine and Coarse Location Permissions Requested?

### ISSUE THREAD

**Issue by nicolasjon** [BaseflowIT/flutter-geolocator#72]
```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```
Just wondered why both of these permissions are requested. I think you only need to request Fine.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@nicolasjon you don't need to supply both the plugin will work with supplying either one of the permissions. Of course the plugin will provide more accurate location updates when supplying the `android.permission.ACCESS_FINE_LOCATION` instead of the `android.permission.ACCESS_COARSE_LOCATION`.

I will update the `README.md` to reflect this behaviour more clearly, thanks for pointing it out.
