### ISSUE TITLE
i get a number in placemarks.name other than a name

### ISSUE THREAD

**Issue by aidooyaw1992** [BaseflowIT/flutter-geolocator#97]
## 🐛 Bug Report

i seem to be getting a number instead of a name when i use
### Expected behavior
I/flutter (27801): 8
### Reproduction steps
List<Placemark> placemarks = await Geolocator()
        .placemarkFromCoordinates(5.6098949, -0.225339);
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@aidooyaw1992 I have done some additional research and also see that using the coordinates you supplied the `Placemark.name` property hold a number value (in my case "76"). 

The `Placemark.name` property is mapped with to the `getFeatureName()` accessor from the `android.location.Address` class which is returned by the `getFromLocation(double latitude, double longitude, int maxResults)` method of the Android `Geocoder` SDK. We don't do any additional processing on it. In other words, this is exactly the value which Google returns to us as "the feature name of the address, for example, "Golden Gate Bridge", or null if it is unknown".

I am not sure what your requirements are, to get more detailed information you might want to use the Google Places API. We don't use this API at the moment because its free use is limited (more information can be found [here](https://cloud.google.com/maps-platform/pricing/sheet/).
